image: ruby:2.3

before_script:
  - apt-get update -qy
  - apt-get install -y nodejs # middleman requires JS runtime
  - bundle install --without development

pages:
  script:
    - bundle exec middleman build
    - mv build/ public
  artifacts:
    paths:
    - public
  only:
    - master
