image: ruby:2.5

variables:
  LC_ALL: "en_US.UTF-8"

cache:
  paths:
    - vendor/

before_script:
  - apt-get update -qy
  - apt-get install -y nodejs # middleman requires JS runtime
  - bundle install --without development --path vendor

pages:
  script:
    - bundle exec middleman build
    - mv build/ public
  artifacts:
    paths:
    - public
  only:
    - master
