image: ruby:2.3

before_script:
  - apt-get update -qy
  - apt-get install -y nodejs # middleman requires JS runtime
  - cd project
  - bundle install --without development --path ../vendor

pages:
  script:
    - bundle exec middleman build
    - cd ..
    - mv project/build/ public
  artifacts:
    paths:
    - public
  only:
    - master
