version: '3.0'

services:
  middleman:
    image: casaper/docker-middleman:0.1
    user: middleman
    volumes:
      - ./project:/middleman/app
      - ./scripts:/middleman/scripts
    ports:
      - "4567:4567"
      - "35729:35729"
    entrypoint:
      - /bin/sh
      - /middleman/scripts/entry.sh
